import React from 'react';

export default function Dashboard() {
  return (
    <div className="dashboard-container">
      {/* Sidebar */}
      <aside className="sidebar">
        <div className="brand">Akshara World</div>
        <nav>
          <div className="nav-item active">
            <span>📊</span> Business KPIs
          </div>
          <div className="nav-item">
            <span>🏢</span> Department Grid
          </div>
          <div className="nav-item">
            <span>💊</span> Capsule Viewer
          </div>
          <div className="nav-item">
            <span>✅</span> Approvals Queue
          </div>
          <div className="nav-item">
            <span>⚙️</span> Resource Inventory
          </div>
          <div className="nav-item">
            <span>📜</span> Change Log
          </div>
        </nav>
      </aside>

      {/* Main Content */}
      <main className="main-content">
        <div className="top-bar">
          <div>
            <h1 style={{ fontSize: '1.5rem', fontWeight: 600 }}>Live Command Center</h1>
            <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', marginTop: '4px' }}>
              System Uptime: 99.99% <span className="status-dot" style={{ marginLeft: '8px' }}></span>
            </p>
          </div>
          <div className="user-profile">
            <span className="auth-badge">Clerk 2FA Secured</span>
            <span>Owner</span>
          </div>
        </div>

        <div className="bento-grid">
          <div className="glass-card">
            <div className="card-title">Daily Revenue</div>
            <div className="card-value">₹0</div>
          </div>
          <div className="glass-card">
            <div className="card-title">Active AI Agents</div>
            <div className="card-value">8</div>
          </div>
          <div className="glass-card">
            <div className="card-title">Pending Approvals</div>
            <div className="card-value" style={{ color: '#f59e0b' }}>0</div>
          </div>
        </div>

        <div className="embed-container">
          {/* Looker Studio / Google Sheets Embed Placeholder */}
          <div style={{ position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%, -50%)', textAlign: 'center' }}>
            <h3 style={{ color: 'var(--text-muted)', marginBottom: '16px' }}>Dashboard Data Layer</h3>
            <p style={{ fontSize: '0.9rem', maxWidth: '400px', lineHeight: '1.5' }}>
              Paste your Google Sheets / Looker Studio embed URL here. The backend was just generated by Sam via Apps Script.
            </p>
          </div>
        </div>
      </main>

      {/* Sam Chat Panel */}
      <aside className="sam-chat-panel">
        <div className="chat-header">
          <div className="sam-avatar">S</div>
          <div>
            <div style={{ fontWeight: 600 }}>Sam (AI CEO)</div>
            <div style={{ fontSize: '0.8rem', color: '#10b981' }}>Online • Gemma 3</div>
          </div>
        </div>
        <div className="chat-messages">
          <div className="message sam">
            Greetings. I am Sam, the AI CEO of Akshara World. I have initialized the Google Drive folders and the backend Dashboard spreadsheet.
          </div>
          <div className="message sam">
            What is your directive for the next phase? I am ready to process the first capsule.
          </div>
        </div>
        <div className="chat-input-container">
          <input type="text" className="chat-input" placeholder="Message Sam..." />
        </div>
      </aside>
    </div>
  );
}
